version: "3"
services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    volumes:
      - ./temp:/temp
      - ~/postgres-data:/var/lib/postgresql/data
    restart: always
  nxb:
    build: .
    volumes:
      - ./temp:/app/temp
      - ./instance:/app/instance
      - logs:/var/log
    environment:
      APP_CONFIG: nxb_config.py
      GUNICORN_CMD_ARGS: --config=instance/gu_config.py
    ports:
      - "8000:8000"
    restart: always
  nginx:
    build:
      context: .
      dockerfile: docker/nginx/Dockerfile
    ports:
      - "80:80"
    volumes:
      - logs:/var/log
    restart: always
volumes:
  logs: {}
