version: "3.4"
services:
  postgres:
    volumes:
      - data:/var/lib/postgresql/data
  nxb:
    build:
      context: .
      target: test
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      PYTHONPATH: .
    entrypoint:
      - /app/.venv/bin/pytest
      - .
volumes:
  data: {}
