version: "3"
services:
  postgres:
    build:
      context: .
      dockerfile: docker/postgres/Dockerfile
    volumes:
      - ./temp:/temp
      - ~/postgres-data:/var/lib/postgresql/data
  nxb:
    build:
      context: .
      target: production
    volumes:
      - ./temp:/temp
    environment:
      NXB_DATABASE_URI: postgresql://prod:hello_world@postgres:5432/nextbus
      NXB_DATABASE_DUMP_PATH: /temp/nxb.db.dump
      NXB_TEMP_DIRECTORY: /temp
      NXB_SECRET_KEY: $NXB_SECRET_KEY
      NXB_GEOLOCATION_ENABLED: $NXB_GEOLOCATION_ENABLED
      NXB_TAPI_ACTIVE: $NXB_TAPI_ACTIVE
      NXB_TAPI_LIMIT: $NXB_TAPI_LIMIT
      NXB_TAPI_ID: $NXB_TAPI_ID
      NXB_TNDS_USERNAME: $NXB_TNDS_USERNAME
      NXB_TNDS_PASSWORD: $NXB_TNDS_PASSWORD
      WEB_CONCURRENCY: 2
    ports:
      - "8000:8000"
    depends_on:
      - postgres
