"""initialise

Revision ID: 54d67d76f3db
Revises: 
Create Date: 2017-10-04 08:24:18.378400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54d67d76f3db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Regions',
    sa.Column('region_code', sa.VARCHAR(length=2), nullable=False),
    sa.Column('region_name', sa.Text(), nullable=True),
    sa.Column('country', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('region_code')
    )
    op.create_table('AdminAreas',
    sa.Column('admin_area_code', sa.VARCHAR(length=3), nullable=False),
    sa.Column('region_code', sa.VARCHAR(length=2), nullable=True),
    sa.Column('atco_area_code', sa.VARCHAR(length=3), nullable=True),
    sa.Column('area_name', sa.Text(), nullable=True),
    sa.Column('area_short_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['region_code'], ['Regions.region_code'], ),
    sa.PrimaryKeyConstraint('admin_area_code')
    )
    op.create_index(op.f('ix_AdminAreas_atco_area_code'), 'AdminAreas', ['atco_area_code'], unique=True)
    op.create_table('Districts',
    sa.Column('nptg_district_code', sa.VARCHAR(length=3), nullable=False),
    sa.Column('admin_area_code', sa.VARCHAR(length=3), nullable=True),
    sa.Column('district_name', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['admin_area_code'], ['AdminAreas.admin_area_code'], ),
    sa.PrimaryKeyConstraint('nptg_district_code')
    )
    op.create_table('Postcodes',
    sa.Column('postcode', sa.VARCHAR(length=8), nullable=False),
    sa.Column('postcode_2', sa.VARCHAR(length=7), nullable=True),
    sa.Column('local_authority_code', sa.VARCHAR(length=9), nullable=True),
    sa.Column('admin_area_code', sa.VARCHAR(length=3), nullable=True),
    sa.Column('easting', sa.Integer(), nullable=True),
    sa.Column('northing', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['admin_area_code'], ['AdminAreas.admin_area_code'], ),
    sa.PrimaryKeyConstraint('postcode'),
    sa.UniqueConstraint('postcode_2')
    )
    op.create_table('StopAreas',
    sa.Column('stop_area_code', sa.VARCHAR(length=10), nullable=False),
    sa.Column('stop_area_name', sa.Text(), nullable=True),
    sa.Column('admin_area_code', sa.VARCHAR(length=3), nullable=True),
    sa.Column('stop_area_type', sa.VARCHAR(length=4), nullable=True),
    sa.Column('easting', sa.Integer(), nullable=True),
    sa.Column('northing', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['admin_area_code'], ['AdminAreas.admin_area_code'], ),
    sa.PrimaryKeyConstraint('stop_area_code')
    )
    op.create_table('Localities',
    sa.Column('nptg_locality_code', sa.VARCHAR(length=7), nullable=False),
    sa.Column('locality_name', sa.Text(), nullable=True),
    sa.Column('admin_area_code', sa.VARCHAR(length=3), nullable=True),
    sa.Column('nptg_district_code', sa.VARCHAR(length=3), nullable=True),
    sa.Column('easting', sa.Integer(), nullable=True),
    sa.Column('northing', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['admin_area_code'], ['AdminAreas.admin_area_code'], ),
    sa.ForeignKeyConstraint(['nptg_district_code'], ['Districts.nptg_district_code'], ),
    sa.PrimaryKeyConstraint('nptg_locality_code')
    )
    op.create_table('StopPoints',
    sa.Column('atco_code', sa.VARCHAR(length=12), nullable=False),
    sa.Column('naptan_code', sa.VARCHAR(length=8), nullable=True),
    sa.Column('desc_common', sa.Text(), nullable=True),
    sa.Column('desc_short', sa.Text(), nullable=True),
    sa.Column('desc_landmark', sa.Text(), nullable=True),
    sa.Column('desc_street', sa.Text(), nullable=True),
    sa.Column('desc_crossing', sa.Text(), nullable=True),
    sa.Column('desc_indicator', sa.Text(), nullable=True),
    sa.Column('nptg_locality_code', sa.VARCHAR(length=7), nullable=True),
    sa.Column('suburb', sa.Text(), nullable=True),
    sa.Column('town', sa.Text(), nullable=True),
    sa.Column('easting', sa.Integer(), nullable=True),
    sa.Column('northing', sa.Integer(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('stop_type', sa.VARCHAR(length=3), nullable=True),
    sa.Column('bearing', sa.VARCHAR(length=1), nullable=True),
    sa.Column('stop_area_code', sa.VARCHAR(length=10), nullable=True),
    sa.Column('admin_area_code', sa.VARCHAR(length=3), nullable=True),
    sa.ForeignKeyConstraint(['admin_area_code'], ['AdminAreas.admin_area_code'], ),
    sa.ForeignKeyConstraint(['nptg_locality_code'], ['Localities.nptg_locality_code'], ),
    sa.ForeignKeyConstraint(['stop_area_code'], ['StopAreas.stop_area_code'], ),
    sa.PrimaryKeyConstraint('atco_code')
    )
    op.create_index(op.f('ix_StopPoints_naptan_code'), 'StopPoints', ['naptan_code'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_StopPoints_naptan_code'), table_name='StopPoints')
    op.drop_table('StopPoints')
    op.drop_table('Localities')
    op.drop_table('StopAreas')
    op.drop_table('Postcodes')
    op.drop_table('Districts')
    op.drop_index(op.f('ix_AdminAreas_atco_area_code'), table_name='AdminAreas')
    op.drop_table('AdminAreas')
    op.drop_table('Regions')
    # ### end Alembic commands ###
